INSERT INTO INSTANCE.FACULTY
	( ABBREVIATION, NAME) VALUES ( 'f5', 'faculty5' );

INSERT INTO INSTANCE.TEACHER
	( ID, NAME, FACULTY, REMARK) VALUES ( 'id4', 'teachname4', 'f5', 'some remark' );

INSERT INTO INSTANCE.PROFESSOR
	( TEACHER_ID, CREDIT_HOUR_ACCOUNT, IS_ACTIVE) VALUES ( 'id4', 0, 1);