INSERT INTO INSTANCE.FACULTY
	( ABBREVIATION, NAME) VALUES ( 'f4', 'faculty4' );

INSERT INTO INSTANCE.TEACHER
	( ID, NAME, FACULTY, REMARK) VALUES ( 'id3', 'teachname3', 'f4', 'some remark' );

INSERT INTO INSTANCE.PROFESSOR
	( TEACHER_ID, CREDIT_HOUR_ACCOUNT, IS_ACTIVE) VALUES ( 'id3', 0, 1);

UPDATE INSTANCE.PROFESSOR SET IS_ACTIVE = 0 WHERE TEACHER_ID = 'id3';