INSERT INTO INSTANCE.FACULTY
	( ABBREVIATION, NAME) VALUES ( 'f1', 'faculty1' );

INSERT INTO INSTANCE.MAJOR
	( ABBREVIATION, NAME, FACULTY) VALUES ( 'm1', 'major1', 'f1' );

INSERT INTO INSTANCE.SUBJECT
	( SUBJECT_NUMBER, SUBJECT_NAME, SUBJECT_TYPE, PLANNED_STUPO_HOURS, PLANNED_SCHEDULE_HOURS, SEMESTER, MAJOR, FACULTY, REMARK) VALUES ('examplenumber', 'examplename','E',10, 10, 1,'m1','f1','some remark' );