INSERT INTO INSTANCE.FACULTY
	( ABBREVIATION, NAME) VALUES ( 'f3', 'faculty3' );

INSERT INTO INSTANCE.TEACHER
	( ID, NAME, FACULTY, REMARK) VALUES ( 'id2', 'teachname2', 'f3', 'some remark' );

INSERT INTO INSTANCE.LECTURER
	( TEACHER_ID, ADDRESS, IS_ACTIVE) VALUES ( 'id2', 'city1 street1 number 2 tk12345', 1 );

UPDATE INSTANCE.LECTURER SET IS_ACTIVE = 0 WHERE TEACHER_ID = 'id2';