INSERT INTO INSTANCE.FACULTY
	( ABBREVIATION, NAME) VALUES ( 'f2', 'faculty2' );

INSERT INTO INSTANCE.TEACHER
	( ID, NAME, FACULTY, REMARK) VALUES ( 'id1', 'teachname1', 'f2', 'some remark' );

INSERT INTO INSTANCE.LECTURER
	( TEACHER_ID, ADDRESS, IS_ACTIVE) VALUES ( 'id1', 'city1 street1 number 1 tk12345', 1 );

